name: JIRA Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - run: |
          echo The PR was merged
